baseURL = 'https://demo.shaheen.homes/'
languageCode = 'en-us'
title = 'My New Website'
theme = 'PaperMod'
author = "Shaheen"
description = "My personal website"

[menu]

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 1


[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects/"
weight = 2


[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 3


[[menu.main]]
    identifier = "home"
    name = "home"
    url = "/home/"
    weight = 4


[params]
  defaultTheme = "light"
  # defaultTheme = "dark"
  # defaultTheme = "auto" # to switch between dark or light according to browser theme
    disableThemeToggle = true

  